name: Trial-Key & Account generator

on:
  schedule:
    - cron: "0 1 9 * *" # Chạy vào 00:00 ngày mùng 1 mỗi tháng
    
  workflow_dispatch:
    inputs:
      account:
        description: 'Number of Accounts to be generated (default = 0)'
        required: false
        default: '0'
      key:
        description: 'Number of Keys to be generated (default = 1)'
        required: false
        default: '1'
      mail:
        description: 'Choose the mail provider to generate license'
        required: true
        type: choice
        options:
        - 1secmail
        - guerrillamail
        - developermail
        - mailticking
        - fakemail
        - inboxes
        default: developermail
      key_type:
        description: 'Modes of operation'
        required: true
        type: choice
        options:
        - --key
        - --small-business-key
        - --vpn-codes
        default: --key
      os:
        description: 'Operating System of runner'
        required: true
        type: choice
        options:
        - macOS
        - Linux
        - Windows
        default: macOS

jobs:
  GenerateKey:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Chrome
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
          chromium-browser --version
          chromedriver --version

      - name: Set default values
        id: set_defaults
        run: |
          # Kiểm tra xem workflow có chạy từ cron hay không
          if [[ "${GITHUB_EVENT_NAME}" == "schedule" ]]; then
            ACCOUNT=0
            KEY=1
            MAIL=1secmail
            KEY_TYPE=--key
            OS=Windows
          else
            ACCOUNT=${{ github.event.inputs.account }}
            KEY=${{ github.event.inputs.key }}
            MAIL=${{ github.event.inputs.mail }}
            KEY_TYPE=${{ github.event.inputs.key_type }}
            OS=${{ github.event.inputs.os }}
          fi
          
          echo "ACCOUNT=${ACCOUNT}" >> $GITHUB_ENV
          echo "KEY=${KEY}" >> $GITHUB_ENV
          echo "MAIL=${MAIL}" >> $GITHUB_ENV
          echo "KEY_TYPE=${KEY_TYPE}" >> $GITHUB_ENV
          echo "OS=${OS}" >> $GITHUB_ENV

      - name: Generate key
        id: generate_key
        run: |
          ACCOUNT=${{ env.ACCOUNT }}
          KEY=${{ env.KEY }}
          MAIL=${{ env.MAIL }}
          KEY_TYPE=${{ env.KEY_TYPE }}
          OS=${{ env.OS }}

          git clone https://github.com/rzc0d3r/ESET-KeyGen.git
          cd ESET-KeyGen
          
          # Setup env
          sudo apt update
          sudo apt install -y python3-pip python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          # Initialize variables
          ACCOUNTS=""
          KEYS=""

          if ($ACCOUNT -ne 0 -and $KEY -ne 0) {
              python3 main.py --chrome --account --email-api $MAIL --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar --repeat $ACCOUNT
              python3 main.py --chrome $KEY_TYPE --email-api $MAIL --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar --repeat $KEY
              echo "Account:" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
              Get-Content -Path ./*ACCOUNTS.txt | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
              echo "`nKey:" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
              Get-Content -Path ./*KEYS.txt | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          }
          elseif ($ACCOUNT -ne 0) {
              python3 main.py --chrome --account --email-api $MAIL --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar --repeat $ACCOUNT
              echo "`nAccount:" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
              Get-Content -Path ./*ACCOUNTS.txt | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          }
          elseif ($KEY -ne 0) {
              python3 main.py --chrome $KEY_TYPE --email-api $MAIL --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar --repeat $KEY
              echo "`nKey:" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
              Get-Content -Path ./*KEYS.txt | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          }
          fi

          # Set environment variables to be used in later steps
          echo "ACCOUNTS=${ACCOUNTS}" >> $GITHUB_ENV
          echo "KEYS=${KEYS}" >> $GITHUB_ENV

      - name: Verify Variables
        run: |
          echo "ACCOUNTS: ${ACCOUNTS}"
          echo "KEYS: ${KEYS}"

      - name: Send email with results
        uses: dawidd6/action-send-mail@v3
        with:
          to: vtdinh92@gmail.com # Địa chỉ email nhận
          subject: "ESET KeyGen Results"
          body: |
            The generation process is complete.
            Accounts: ${{ env.ACCOUNTS }}
            Keys: ${{ env.KEYS }}
          from: vtdinh92@gmail.com # Địa chỉ email gửi
          server_address: smtp.gmail.com
          server_port: 587 # Cổng 587 cho TLS
          username: vtdinh92@gmail.com
          password: ${{ secrets.SMTP_PASSWORD }} # Sử dụng biến bí mật
          secure: false # Kết nối bảo mật (TLS)
