name: Trial-Key & Account generator

on:
  schedule:
    - cron: "0 0 1 * *"  # Chạy vào 00:00 ngày 1 hàng tháng
  workflow_dispatch:
    inputs:
      account:
        description: 'Number of Accounts to be generated (default = 0)'
        required: false
        default: '0'
      key:
        description: 'Number of Keys to be generated (default = 1)'
        required: false
        default: '1'
      mail:
        description: 'Choose the mail provider to generate license'
        required: true
        type: choice
        options:
        - 1secmail
        - guerrillamail
        - developermail
        - mailticking
        - fakemail
        - inboxes
        default: developermail
      key_type:
        description: 'Modes of operation'
        required: true
        type: choice
        options:
        - --key
        - --small-business-key
        - --vpn-codes
        default: --key
      os:
        description: 'Operating System of runner'
        required: true
        type: choice
        options:
        - macOS
        - Linux
        - Windows
        default: Linux

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate key (Linux)
        if: github.event.inputs.os == 'Linux' || github.event_name == 'schedule'
        run: |
          ACCOUNT=${{ github.event.inputs.account || '0' }}
          KEY=${{ github.event.inputs.key || '1' }}
          MAIL=${{ github.event.inputs.mail || 'developermail' }}
          KEY_TYPE=${{ github.event.inputs.key_type || '--key' }}

          git clone https://github.com/rzc0d3r/ESET-KeyGen.git
          cd ESET-KeyGen
          
          # Setup env
          sudo apt update
          sudo apt install -y python3-pip python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          if [[ ${ACCOUNT} -ne 0 && ${KEY} -ne 0 ]]; then
            python3 main.py --chrome --account --email-api ${MAIL} --repeat ${ACCOUNT}
            python3 main.py --chrome ${KEY_TYPE} --email-api ${MAIL} --repeat ${KEY}
            echo "Account:" >> $GITHUB_STEP_SUMMARY
            cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
            echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
            cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
          elif [[ ${ACCOUNT} -ne 0 ]]; then
            python3 main.py --chrome --account --email-api ${MAIL} --repeat ${ACCOUNT}
            echo -e "\nAccount:" >> $GITHUB_STEP_SUMMARY
            cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
          elif [[ ${KEY} -ne 0 ]]; then
            python3 main.py --chrome ${KEY_TYPE} --email-api ${MAIL} --repeat ${KEY}
            echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
            cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
          fi

      - name: Send email with results (Linux)
        uses: dawidd6/action-send-mail@v3
        with:
          to: vtdinh92@gmail.com
          subject: "ESET KeyGen Results (Linux)"
          body: |
            The generation process is complete.
            See the attached keys and accounts.
          from: vtdinh92@gmail.com
          server_address: smtp.gmail.com
          server_port: 587
          username: vtdinh92@gmail.com
          password: ${{ secrets.SMTP_PASSWORD }}
          secure: false
          attachments: ./*KEYS.txt, ./*ACCOUNTS.txt

  macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate key (macOS)
        if: github.event.inputs.os == 'macOS'
        run: |
          ACCOUNT=${{ github.event.inputs.account }}
          KEY=${{ github.event.inputs.key }}
          MAIL=${{ github.event.inputs.mail }}
          KEY_TYPE=${{ github.event.inputs.key_type }}

          git clone https://github.com/rzc0d3r/ESET-KeyGen.git
          cd ESET-KeyGen
          
          brew install python
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          python3 main.py --chrome ${KEY_TYPE} --email-api ${MAIL} --repeat ${KEY}

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate key (Windows)
        if: github.event.inputs.os == 'Windows'
        run: |
          $ACCOUNT="${{ github.event.inputs.account }}"
          $KEY="${{ github.event.inputs.key }}"
          $MAIL="${{ github.event.inputs.mail }}"
          $KEY_TYPE="${{ github.event.inputs.key_type }}"

          git clone https://github.com/rzc0d3r/ESET-KeyGen.git
          cd ESET-KeyGen

          pip install -r requirements.txt

          python3 main.py --chrome --account --email-api $MAIL --repeat $ACCOUNT
          python3 main.py --chrome $KEY_TYPE --email-api $MAIL --repeat $KEY
