      - name: Generate key
        id: generate_key
        run: |
          ACCOUNT=${{ github.event.inputs.account }}
          KEY=${{ github.event.inputs.key }}
          MAIL=${{ github.event.inputs.mail }}
          KEY_TYPE=${{ github.event.inputs.key_type }}

          git clone https://github.com/rzc0d3r/ESET-KeyGen.git
          cd ESET-KeyGen
          
          # Setup env
          sudo apt update
          sudo apt install -y python3-pip python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          # Initialize variables
          ACCOUNTS=""
          KEYS=""

          if [[ ${ACCOUNT} -ne 0 && ${KEY} -ne 0 ]]; then
            seq 1 ${ACCOUNT} | xargs -I {} -P ${ACCOUNT} python3 main.py --chrome --account --email-api ${MAIL} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar &
            seq 1 ${KEY} | xargs -I {} -P ${KEY} python3 main.py --chrome ${KEY_TYPE} --email-api ${MAIL} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar
            wait
            # Read accounts and keys from files
            ACCOUNTS=$(cat ./*ACCOUNTS.txt | tr '\n' ', ')
            KEYS=$(cat ./*KEYS.txt | tr '\n' ', ')
          elif [[ ${ACCOUNT} -ne 0 ]]; then
            seq 1 ${ACCOUNT} | xargs -I {} -P ${ACCOUNT} python3 main.py --chrome --account --email-api ${MAIL} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar
            ACCOUNTS=$(cat ./*ACCOUNTS.txt | tr '\n' ', ')
          elif [[ ${KEY} -ne 0 ]]; then
            seq 1 ${KEY} | xargs -I {} -P ${KEY} python3 main.py --chrome ${KEY_TYPE} --email-api ${MAIL} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar
            KEYS=$(cat ./*KEYS.txt | tr '\n' ', ')
          fi

          # Set environment variables to be used in later steps
          echo "ACCOUNTS=${ACCOUNTS}" >> $GITHUB_ENV
          echo "KEYS=${KEYS}" >> $GITHUB_ENV

      - name: Verify Variables
        run: |
          echo "ACCOUNTS: ${ACCOUNTS}"
          echo "KEYS: ${KEYS}"

      - name: Send email with results
        uses: dawidd6/action-send-mail@v3
        with:
          to: vtdinh92@gmail.com # Địa chỉ email nhận
          subject: "ESET KeyGen Results"
          body: |
            The generation process is complete.
            Accounts: ${{ env.ACCOUNTS }} # Sử dụng biến môi trường
            Keys: ${{ env.KEYS }} # Sử dụng biến môi trường
          from: vtdinh92@gmail.com # Địa chỉ email gửi
          server_address: smtp.gmail.com
          server_port: 587 # Cổng 587 cho TLS
          username: vtdinh92@gmail.com
          password: ${{ secrets.SMTP_PASSWORD }} # Sử dụng biến bí mật
          secure: false # Kết nối bảo mật (TLS)
